### Site info:
title: Alex Wang's Site
tagline: Making Everyday Interesting
author: Alexander Wang
email: alwang85@gmail.com
description: "A coder's retrospective." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
locale: en_US
teaser: "https://placehold.it/280x200"

### Personal info and site tools info:
twitter_username: alwang85
github_username:  alwang85
stackoverflow_username: 2026166/alwang85
disqus_shortname: alwang85
favicon:     "/images/favicon.ico"
aboutme: Hi, this is Alex Wang. Thanks for visiting! # these are shown on aboutme-sidebar.
aboutme_photo: http://i.imgur.com/MaGQ67c.jpg # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

#Blogroll:
#    - name: Freshman21
#      href: http://yulijia.net/freshman21
#      title: Another Jekyll blog theme
#    - name: author's website
#      href: http://yulijia.net/
#      title: Lijia Yu's website


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5

collections:
  projects:
    output: true